name: stride
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - blosc
  - cached-property
  - click
  - cloudpickle>=1.6
  - cython
  - flake8
  - gputil
  - h5py>=3.2
  - matplotlib>=3.4
  - nbval
  - numpy>=1.20
  - notebook>=6.4
  - pickle5
  - pip
  - pre-commit>=2.13
  - psutil
  - pyflakes
  - pytest
  - pytest-cov
  - pyyaml>=5.4
  - pytest-runner
  - pyzmq>=22.1
  - scikit-image
  - scipy>=1.6
  - sphinx
  - sphinx_rtd_theme
  - tornado>=6.1
  - traitsui
  - wxPython
  - zlib
  - pip:
      - devito>=4.6
      - python-daemon
