name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - fw3d_match
  pull_request:
    branches:
      - master

jobs:
  examples:
    name: Examples
    runs-on: ubuntu-latest

    env:
      DEVITO_COMPILER: gcc-7
      DEVITO_LANGUAGE: "openmp"
      PYTHON_VERSION: "3.7"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

    steps:
    - name: Checkout stride
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
       activate-environment: stride
       environment-file: environment.yml
       python-version: 3.7
       auto-activate-base: false

    - name: Install dependencies
      # See setup-miniconda README, necessary to activate environment
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Homogeneous examples
      shell: bash -l {0}
      run: |
        mrun -nw 1 -nth 2 python examples/stride/homogeneous/forward_2D.py
      # mrun -nw 1 -nth 2 python examples/stride/homogeneous/forward_3D.py
    - name: Breast 2D
      shell: bash -l {0}
      run: |
        mrun -nw 1 -nth 2 python examples/stride/breast2D/03_script_forward.py
        mrun -nw 1 -nth 2 python examples/stride/breast2D/04_script_inverse.py
